src/Entity/Contacts.php
<?php

namespace App\Entity;

use App\Repository\ContactsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ContactsRepository::class)
 */
class Contacts
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $email;

    /**
     * @ORM\Column(type="bigint")
     */
    private $MobileNumber;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getMobileNumber(): ?string
    {
        return $this->MobileNumber;
    }

    public function setMobileNumber(string $MobileNumber): self
    {
        $this->MobileNumber = $MobileNumber;

        return $this;
    }
}

src/Form/ContactsType.php
<?php

namespace App\Form;

use App\Entity\Contacts;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContactsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('mobile_number')
            ->add('email')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Contacts::class,
        ]);
    }
}

src/Controller/ContactsController.php
<?php

namespace App\Controller;

use App\Entity\Contacts;
use App\Form\ContactsType;
use App\Repository\ContactsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/contacts")
 */
class ContactsController extends AbstractController
{
    /**
     * @Route("/", name="app_contacts_index", methods={"GET"})
     */
    public function index(ContactsRepository $contactsRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        return $this->render('contacts/index.html.twig', [
            'contacts' => $contactsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_contacts_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ContactsRepository $contactsRepository): Response
    {
        $contact = new Contacts();
        $form = $this->createForm(ContactsType::class, $contact);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $contactsRepository->add($contact);
            return $this->redirectToRoute('app_contacts_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('contacts/new.html.twig', [
            'contact' => $contact,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_contacts_show", methods={"GET"})
     */
    public function show(Contacts $contact): Response
    {
        return $this->render('contacts/show.html.twig', [
            'contact' => $contact,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_contacts_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Contacts $contact, ContactsRepository $contactsRepository): Response
    {
        $form = $this->createForm(ContactsType::class, $contact);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $contactsRepository->add($contact);
            return $this->redirectToRoute('app_contacts_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('contacts/edit.html.twig', [
            'contact' => $contact,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_contacts_delete", methods={"POST"})
     */
    public function delete(Request $request, Contacts $contact, ContactsRepository $contactsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$contact->getId(), $request->request->get('_token'))) {
            $contactsRepository->remove($contact);
        }

        return $this->redirectToRoute('app_contacts_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/contacts/_delete_form.html.twig
<form method="post" action="{{ path('app_contacts_delete', {'id': contact.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ contact.id) }}">
    <button class="btn btn-warning">Delete</button>
</form>

templates/contacts/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/contacts/edit.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Edit Contacts{% endblock %}

{% block content %}
    <h1 class="h3 mb-2 text-gray-800">Edit Contacts
    <div class="col-6 float-right text-right">
    <div class="col-6 float-right text-right">
            <div>
                <div class="col-* ml-2 float-right">
                    {{ include('contacts/_delete_form.html.twig') }}
                </div>
                <div class="col-*">
                    <a class="btn btn-dark" href="{{ path('app_contacts_index') }}">back to list</a>
                </div>
            </div>
            
            </div>
    </h1>

     {{ include('contacts/_form.html.twig', {'button_label': 'Update'}) }}
   
{% endblock %}

templates/contacts/index.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Contacts index{% endblock %}

{% block content %}
    <h1 class="h3 mb-2 text-gray-800">Contacts</h1>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Contact List</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                            <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Mobile</th>
                                <th>Email</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Mobile</th>
                                <th>Email</th>
                                <th>Actions</th>
                            </tr>
                        </tfoot>
                        <tbody>
                        {% for contact in contacts %}
                            <tr>
                                <td>{{ contact.id }}</td>
                                <td>{{ contact.name }}</td>
                                <td>{{ contact.mobileNumber }}</td>
                                <td>{{ contact.email }}</td>
                                <td>
                                    <a href="{{ path('app_contacts_show', {'id': contact.id}) }}">show</a>
                                    <a href="{{ path('app_contacts_edit', {'id': contact.id}) }}">edit</a>
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="5">No records found</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    <a class="btn btn-primary" href="{{ path('app_contacts_new') }}">Create new</a>
{% endblock %}
 {% block stylesheets %}
<!-- Custom styles for this page -->
    <link href="{{ asset('sb-admin-2/vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
{% endblock %}

{% block javascripts %}
<!-- Page level plugins -->
    <script src="{{ asset('sb-admin-2/vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('sb-admin-2/vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

    <!-- Page level custom scripts -->
    <script src="{{ asset('sb-admin-2/js/demo/datatables-demo.js') }}"></script>
{% endblock %}

templates/contacts/new.html.twig
{% extends 'layout.html.twig' %}

{% block title %}New Contact{% endblock %}

{% block content %}
    <h1 class="h3 mb-2 text-gray-800">New Contact
    <div class="col-6 float-right text-right">
    <a class="btn btn-dark" href="{{ path('app_contacts_index') }}">back to list</a>
    </div>
    </h1>

    {{ include('contacts/_form.html.twig') }}

    
{% endblock %}

templates/contacts/show.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Contacts{% endblock %}

{% block content %}
    <h1 class="h3 mb-2 text-gray-800">Contacts</h1>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Contact List
            <div class="col-6 float-right text-right">
            <div>
                <div class="col-* ml-2 float-right">
                    {{ include('contacts/_delete_form.html.twig') }}
                </div>
                <div class="col-*">
                    <a class="btn btn-dark" href="{{ path('app_contacts_index') }}">back to list</a>
                </div>
            </div>
            
            </div>
            </h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Mobile</th>
                            <th>Email</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Mobile</th>
                            <th>Email</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        <tr>
                            <td>{{ contact.id }}</td>
                            <td>{{ contact.name }}</td>
                            <td>{{ contact.mobileNumber }}</td>
                            <td>{{ contact.email }}</td>
                        </tr>
                    </tbody>
                </table>
                </div>
            </div>
        </div>
    <a class="btn btn-primary" href="{{ path('app_contacts_edit', {'id': contact.id}) }}">edit</a>
{% endblock %}

{% block stylesheets %}
<!-- Custom styles for this page -->
    <link href="{{ asset('sb-admin-2/vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
{% endblock %}

{% block javascripts %}
<!-- Page level plugins -->
    <script src="{{ asset('sb-admin-2/vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('sb-admin-2/vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

    <!-- Page level custom scripts -->
    <script src="{{ asset('sb-admin-2/js/demo/datatables-demo.js') }}"></script>
{% endblock %}